export default function Head() {
  return (
    <>
      <title>extra job</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://extra-job.co.il/wp-content/uploads/2021/02/cropped-FAVI-32x32.png" />
        {/*<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.rtl.min.css"*/}
        {/*      integrity="sha384-DOXMLfHhQkvFFp+rWTZwVlPVqdIhpDVYT9csOnHSgWQWPX0v5MCGtjCJbY6ERspU"*/}
        {/*      crossOrigin="anonymous"/>*/}

        </>
  )
}
