export default function Head() {
  return (
    <>
      <title>extra job</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://extra-job.co.il/wp-content/uploads/2021/02/cropped-FAVI-32x32.png" />
        </>
  )
}
